/**
 * Represents a single work experience entry stored in a database.
 */
export type WorkExperienceEntity = {
  /** Unique identifier */
  id: string;
  /** Company name */
  companyName: string;
  /** Job title */
  jobTitle: string;
  /** Workplace city location */
  workCityLocation: string;
  /** Job start date */
  startDate: Date;
  /** Job end date */
  endDate: Date;
  /** Job description */
  description: string;
};

/**
 * Payload used for creating a new work experience via API.
 * Omits the `id` field since it is generated by the database.
 */
export type WorkExperiencePayload = Omit<WorkExperienceEntity, "id">;

/**
 * Payload used for inserting into the SQLite database.
 * Based on the API payload, but uses ISO 8601 strings for date fields because SQLite stores them as TEXT.
 */
export type WorkExperienceDbPayload = Omit<
  WorkExperiencePayload,
  "startDate" | "endDate"
> & {
  startDate: string; // ISO 8601 format
  endDate: string; // ISO 8601 format
};
